name: Publish
on:
  push:
    branches:
      - main
      - next/**
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Git User Name
        run: git config user.name "GitHub Actions"
      - name: Set Git User Email
        run: git config user.email "actions@users.noreply.github.com"
      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - name: Install Dependencies
        run: node common/scripts/install-run-rush.js install --no-link
      - name: Link Dependencies
        run: node common/scripts/install-run-rush.js link
      - name: Check Changes
        run: node common/scripts/install-run-rush.js change --verify
      - name: Publish Latest
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main') }}
        run: node common/scripts/install-run-rush.js publish --set-access-level public --target-branch main --add-commit-details --apply --publish
        env:
          NPM_AUTH_TOKEN: '${{ secrets.NPM_PUBLISH_TOKEN }}'
      - name: Publish Next
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/next') }}
        run: node common/scripts/install-run-rush.js publish --set-access-level public --target-branch next --add-commit-details --apply --publish --tag next
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
